displayName: Public Dynamic IP Whitelist
type: provider

import: github.com/KCL-Electronics/traefik-cdn-whitelist/v2

summary: 'Public Dynamic IP Whitelist Plugin'

testData:
  provider: cloudflare,fastly
  pollInterval: "120s"
  whitelistIPv6: true
  additionalSourceRange:
    - 127.0.0.1/32
  
